name: 'AWS Credentials Provisioning'
description: 'Install AWS credentials that can be used by subsequent steps'
author: 'The Guardian'
inputs:
  awsRoleToAssume:
    description: 'The ARN of the AWS role which can be assumed by GHA'
    required: true
  awsRegion:
    description: 'The AWS region'
    default: 'eu-west-1'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
