name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  workflow_dispatch:
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: printenv
      - uses: guardian/actions-assume-aws-role@hackday
        with:
          awsRoleToAssume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
      - run: aws s3 cp README.md s3://riffraff-artifact/akash/README.md
